site_name: Vitacore
site_url: https://vitacore.ru/
repo_name: vitacore-company/runtime
repo_url: https://github.com/vitacore-company/runtime
edit_uri: ""
copyright: Copyright &copy; 2024 Vitacore. All Rights Reserved.
extra:
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/vitacore-company/
  - icon: material/home
    link: https://vitacore.ru/
extra_css:
  - css/custom.css
theme:
  name: "material"
  language: "ru"
  palette:
    - scheme: "default"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - toc:
      toc_depth: 3
plugins:
  - glightbox
  - search:
      lang: ru
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_signature_annotations: true
            show_source: false
            show_bases: false
            show_root_toc_entry: false
